
// Client generated by Neon v0.0.0 (https://github.com/roblaudio/neon)

export declare const sendEvents: () => void

export declare const EventFromClient: {
fire: () => void
}

export declare const EventFromServer: {
on: () => void
}

export declare const FunctionFromServer: {
invoke: () => void
}
