
// Server generated by Neon v0.0.0 (https://github.com/roblaudio/neon)

export declare const sendEvents: () => void

export declare const EventFromClient: {
on: () => void
};

export declare const EventFromServer: {
fire: () => void
fireAll: () => void
fireList: () => void
fireExcept: () => void
};

export declare const FunctionFromServer: {
setCallback: (callback: () => void) => () => void
};
